### ISSUE TITLE
About box issue

### ISSUE THREAD

**Issue by bovirus** [HakanL/resxtranslator#47] opened 2020-02-29 16:51 UTC
@Klocman

Now version could **_2.9.xxxx.x.xxx_**

Copyright Hakan Lindestaf **_2010_** for me could be **_2020_**

Now in the About box there is a **Company name:** without the name of company

![image](https://user-images.githubusercontent.com/1262554/75611590-1bb0b980-5b1c-11ea-8627-a689587572d0.png)

**Comment by Klocman** [comment] 2020-02-29 17:47
Duplicate of #46

**Closed by Klocman** 2020-02-29 17:47 UTC
