### ISSUE TITLE
Enhancement - Save automatically dialog/columns  size/position

### ISSUE THREAD

**Issue by bovirus** [HakanL/resxtranslator#51] opened 2020-03-01 08:34 UTC
@HakanL 

Currently the program don't save dialog/column size/positiion.
Then every time that I re-run the exe file I have to resize the columns/windows as I like.

Could be possible to modify the source code to save dialog/columns size/position?

Thanks.

**Comment by Klocman** [comment] 2020-03-01 23:46
I added saving of panel sizes. Dialog positions always show in the center of the main window to make sure they are easy to find. Main window size and position was already saved. Is there anything else that could be saved?

**Comment by bovirus** [comment] 2020-03-02 07:59
Now it works fine.  Thanks.
I suppose that you enable the saving for all main items of the interface.

**_Small OT_**
I need your help (for your Visual C knowledge) about a project to enable it as multilanguage.

Please check here https://github.com/kingfisher63/avm_juischeck/issues/5

If you want to help me please post me your suggestion to bovirus at gmail . com

I will delete the text of small OT afterwards.

**Comment by Klocman** [comment] 2020-03-02 16:38
To add translation you need to open controls/forms with visual studio in preview mode, select the top and change Localizable to true. Then you can select which language to add. For strings in code you can move them to a separate .resx file. This can be mostly automated by using resharper's Move... command on the string.

Since the issue is solved I'm closing it.

**Closed by Klocman** 2020-03-02 16:38 UTC

**Comment by Klocman** [comment] 2020-03-02 16:41
Let me know if you are planning to add or suggest any more improvements. I'm planning on releasing a new version tomorrow.

**Comment by bovirus** [comment] 2020-03-02 16:46
You can close.
No add other features.
